# give 2 tries to correctly log in.
limit_req zone=auth burst=2 nodelay;


add_header Set-Cookie "LOGIN-rl-bypass=SomeRandomBytes;Max-Age=15552000;Domain=$host;Path=/;HttpOnly";


satisfy any;
allow 192.168.40.0/21; # 40.1 - 47.1
allow 192.168.137.0/24;
#   allow 192.168.2.0/24;
auth_pam "Authentication Required";
auth_pam_service_name "nginx";