#cloud-config

# This is a sample cloud-init configuration file for setting up a Mirte cloud environment.
# This will replace the default cloud-init configuration.
# It needs to include the files from /media/MIRTE_SETTINGS/config.yaml and /media/MIRTE_SETTINGS/first-boot.sh
# on first boot.

datasource_list: [ NoCloud ]
datasource:
  NoCloud:
    # read from boot partition instead of partition with cidata label as
    fs_label: MIRTE_SETTI # label is max 11 chars
    # seedfrom: # KEEP this commented to trigger ds-identify to find the datasource

mounts:
  - [ /dev/disk/by-label/MIRTE_SETTI, /media/MIRTE_SETTINGS, auto, "defaults,nofail", "0", "2" ]
  # overlay mount possibly


cloud_init_modules:
  - set_hostname
  - update_hostname
  - ssh
  - mounts
  # - set_passwords # handled by mirte-module

cloud_config_modules:
  - ssh_import_id

cloud_final_modules:
  - scripts-per-once
  - scripts-per-boot
  - scripts-user


warnings:                                                              #
  dsid_missing_source: off


