name: CMake Format Check

on:
  [push, pull_request]

jobs:
  cmake-format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install cmake-format
        run: pip install cmake-format

      - name: Run cmake-format check
        run: cmake-format --check **/**/CMakeLists.txt

