name: test-install-parts

on: [push, pull_request]

jobs:
  arduino-install:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - shell: bash
      run: |
        mkdir -p /etc/udev/rules.d/ # just for testing, folder should just exist on the real image
        sudo useradd -m -s /bin/bash mirte 
        MIRTE_SRC_DIR=/usr/local/src/mirte
        ls -ld /usr/local/
        ls -ld /usr/local/src/
        sudo mkdir -p $MIRTE_SRC_DIR
        sudo mkdir $MIRTE_SRC_DIR/mirte-install-scripts/
        sudo cp -r ./* $MIRTE_SRC_DIR/mirte-install-scripts/
        cd $MIRTE_SRC_DIR
        sudo apt update
        sudo git clone https://github.com/mirte-robot/telemetrix4arduino.git mirte-telemetrix4arduino -b develop
        sudo git clone https://github.com/mirte-robot/telemetrix4rpipico.git mirte-telemetrix4rpipico -b develop --recursive
        cd $MIRTE_SRC_DIR/mirte-install-scripts/
        sudo ./install_arduino.sh

  ros2-install:
    runs-on: ubuntu-22.04
    container: ghcr.io/catthehacker/ubuntu:act-22.04
    strategy:
      matrix:
        type: [mirte, mirte-master]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - shell: bash
      run: |
        echo $0
        sudo useradd -m -s /bin/bash mirte
        # allow nopasswd sudo for mirte user
        echo "mirte ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/mirte
        sudo chmod 777 /home/runner/ || true
        MIRTE_SRC_DIR=/usr/local/src/mirte
        sudo mkdir -p $MIRTE_SRC_DIR
        sudo chown mirte: $MIRTE_SRC_DIR
        sudo chmod 755 $MIRTE_SRC_DIR
        sudo -u mirte mkdir $MIRTE_SRC_DIR/mirte-install-scripts/
        sudo -u mirte cp -r ./* $MIRTE_SRC_DIR/mirte-install-scripts/
        cd $MIRTE_SRC_DIR
        sudo -u mirte git clone https://github.com/arendjan/mirte-ros-packages.git mirte-ros-packages -b develop --recursive

        sudo apt update
        cd $MIRTE_SRC_DIR/mirte-install-scripts/
        sudo -u mirte sed -i '/systemctl/d' install_ROS2.sh # remove systemctl command as it is not available in the github runner/container

        # TODO: add deb proxy if wanted
        # sudo apt install dbus libunwind-dev squid-deb-proxy-client -y
        # mkdir -p /run/dbus
        # dbus-daemon --system
        # # sed -i 's/.*enable-dbus=.*/enable-dbus=no/' /etc/avahi/avahi-daemon.conf
        # avahi-daemon -D &
        MIRTE_TYPE=${{ matrix.type }}
        sudo -u mirte /bin/bash -c "MIRTE_TYPE=${{ matrix.type }} source ./install_ROS2.sh"